name: RouteTesting
on:
  pull_request:
    branches: [main, master]
jobs:
  route_tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: pricepinion
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Install Mongosh
        run: |
          sudo apt-get install gnupg
          wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          mongosh --version
      - name: Insert MongoDB Test Data
        run: |
          cd 
          mongosh --file ../../createDB/populateDB.js
          
      - name: Verify MongoDB data
        run: |
          mongosh --eval '
          const count = db.collection("pricepinion").countDocuments();
          print(`Number of documents in the collection: ${count}`);
          '