# .github/workflows/tests_wrapper.yml
name: Run all tests
on:
  push:
    branches:
      - main
jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit_tests.yml
  
  run-route-tests:
    uses: ./.github/workflows/route_tests.yml
    secrets:
      MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}

  success-check:
    runs-on: ubuntu-latest
    needs: [run-unit-tests, run-route-tests]
    steps:
      - run: echo "Both tests passed. Proceeding to deploy..."
