# .github/workflows/tests_wrapper.yml
name: Run all tests
on:
  push:
    branches:
      - main
jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit_tests.yml
  
  run-route-tests:
    uses: ./.github/workflows/route_tests.yml

  success-check:
    runs-on: ubuntu-latest
    needs: [run-unit-tests, run-route-tests]
    steps:
      - run: echo "Both tests passed. Proceeding to deploy..."
